[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "acfe"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "redis",
    "confluent-kafka",
    "numpy",
    "pydantic"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=acfe"
testpaths = [
    "tests",
]
