apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acfe-ingress
  namespace: acfe
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.acfe.com
    secretName: acfe-tls
  rules:
  - host: api.acfe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: acfe-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: acfe-backend
            port:
              number: 80
